# Generated by Django 4.2.25 on 2025-10-08 16:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0004_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavouritePost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favourites', to='blog.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favourite_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Favourite Post',
                'verbose_name_plural': 'Favourite Posts',
                'ordering': ['-created_on'],
                'unique_together': {('post', 'user')},
            },
        ),
    ]
