# Generated by Django 4.2.25 on 2025-10-08 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_favouritepost'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['created_on']},
        ),
        migrations.RemoveField(
            model_name='post',
            name='updated_on',
        ),
    ]
