# Generated by Django 4.2.25 on 2025-10-09 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_comment_approved'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favouritepost',
            options={'ordering': ['-created_on']},
        ),
    ]
