# Generated by Django 4.2.25 on 2025-10-09 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_favouritepost_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favouritepost',
            options={'ordering': ['-created_on'], 'verbose_name': 'Favourite Post', 'verbose_name_plural': 'Favourite Posts'},
        ),
    ]
